---
name: sprint12_cicd_pipeline
on:
  push:
    tags: ['v[0-9].[0-9]+.[0-9]+']

permissions: { }

jobs:
  test:
    name: Running test.
    runs-on: ubuntu-latest
    container: golang:1.22.2
    steps:
 - uses: actions/checkout@v4

 - name: Run Unit Tests
        run: GOOS=linux GOARCH=amd64 go test -v ./... -count=1

 - name: Vet
        run: go vet ./...
  
  build: 
    name: Checking on build.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
 - uses: actions/setup-go@v5
        with:
          go-version: '^1.22.2'

 - name: Build
        run: go build -v ./...

  lint:
    name: Checking with Lint.
    runs-on: ubuntu-latest
    needs: [test, build ]
    
    permissions:
      contents: read
      packages: read
      statuses: write
    
    steps:
 - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
 - name: Super-linter
        uses: super-linter/super-linter@v6.4.0
        env:
          VALIDATE_SHELL_SHFMT: false
          VALIDATE_BASH_EXEC: false
          VALIDATE_GO: false
          DEFAULT_BRANCH: first-steps
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: [test, build, lint ]
    if: startsWith(github.ref, 'refs/tags')
    steps:
 - name: Checkout
        uses: actions/checkout@v4

 - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

 - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
 - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ra1nz0r/sprint12_cicd_pipeline

 - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta. outputs.labels }}
